### ISSUE TITLE
Support custom line formats [templates]

### ISSUE THREAD

**Issue by fpliger** [spyder-ide/loghub#10]
It'd be great to support custom formats (as cmd line argument string or as format template file) to let users change line format based on their needs. If users know the available env variables they can use it in their format specs. 

The specific format I have in mind in this case includes the tags of the issue. 

Related parts:

https://github.com/spyder-ide/loghub/blob/master/loghub/main.py#L177-L180
https://github.com/spyder-ide/loghub/blob/master/loghub/main.py#L22-L25

Maybe changing [format_changelog](https://github.com/spyder-ide/loghub/blob/master/loghub/main.py#L142) to also accept formatter objects (instead of only format strings) would let users have custom format logic that can easily extend the custom behaviour?

**Comment by goanpeca** [comment]
@fpliger I think I would rather expose a config option to use jinja templates. I can update the current logic so that loghub by default uses some default template but user can use their own templates this way it is much easier (I think) than having formatters.

`loghub spyder-ide/loghub -m v0.1 --template sometemplate.txt`
