### ISSUE TITLE
Add ability to group pull requests by labels

### ISSUE THREAD

**Issue by djhoese** [spyder-ide/loghub#90]
My projects tend to have a lot of pull requests for new features and bug fixes that don't get a corresponding issue created. It seems `loghub` only groups issues. I'm willing to add this feature if it is something you are willing to add to the project.

It might be easiest as a single flag to say "include pull requests in groups".

**Comment by ccordoba12** [comment]
> It might be easiest as a single flag to say "include pull requests in groups".

Sure, please go for it :+1:

**Comment by djhoese** [comment]
@ccordoba12 I'm looking at the `changelog_groups.txt` template and it looks like if I want to do this and make it look good I'll need to make a whole new template. I'll finish implementing it and see how the default template ends up looking.

**Comment by goanpeca** [comment]
@davidh-ssec as in the PR in general I don't think

>My projects tend to have a lot of pull requests for new features and bug fixes that don't get a corresponding issue created.

Is a good practice, and you think that yourself, and I understand that because you work alone on your projects and doing all that is probably "not a priority" or "too much work" but I think it misses the point.

Also, it might make the logic a bit more cumbersome than it already is.

**Comment by djhoese** [comment]
@goanpeca See my comments on the PR.
