### ISSUE TITLE
Add user to rendered changelog

### ISSUE THREAD

**Issue by pydanny** [spyder-ide/loghub#95]
Concept:

###############################################################################
### Pull Requests Merged

* [PR 1](https://github.com/pydanny/arepa/pull/1) - Initial Update, by @goanpeca 

In this release 1 pull request was closed.

###############################################################################

**Comment by pydanny** [comment]
Having this feature added would be very useful for the Cookiecutter community.

**Comment by goanpeca** [comment]
@pydanny I like it :-), pretty straight forward to add :-)

**Comment by goanpeca** [comment]
@djhoese  what do you think of this?

**Comment by djhoese** [comment]
@goanpeca @pydanny Does using the `@` make every new release notify an author (either in a github release or as a commit of a changelog file)? Before switching to `loghub` I had been using [gitchangelog](https://github.com/vaab/gitchangelog) which uses brackets `[David Hoese]` as opposed to the username. Might also look better than seeing `, by X` after every PR. Since it is possible to change your username maybe it would be better to use the accounts name? Just ideas, not necessarily thinking it needs changing. Regardless someone can customize their template if they want once the information is made available.

**Comment by goanpeca** [comment]
I do not think that github will notify users about @username being used on a markdown file within the repo. If that was the case then

[username]  could be used, since not everyone provides a "real name", so usernames are better.

Thoughts @pydanny @ccordoba12 ?

**Comment by djhoese** [comment]
For what it's worth the github changelog generator project does usernames in markdown by doing:

```
[djhoese](https://github.com/djhoese)
```

https://github.com/github-changelog-generator/github-changelog-generator

**Comment by goanpeca** [comment]
Ok, much better :-) will add that one

**Comment by goanpeca** [comment]
So something like this:

![image](https://user-images.githubusercontent.com/3627835/75079330-5e4c1380-54d6-11ea-9243-2610c0b2f629.png)
